name: training_flutter_firebase
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^9.0.0
  dio: ^5.0.1
  flutter_riverpod: ^2.1.1
  firebase_messaging: ^14.2.5
  firebase_core: ^2.7.0
  flutter_local_notifications: ^15.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
